-- MySQL Script generated by MySQL Workbench
-- Mon Sep 27 19:36:25 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bank
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bank
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bank` DEFAULT CHARACTER SET utf8 ;
USE `bank` ;

-- -----------------------------------------------------
-- Table `bank`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank`.`users` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bank`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank`.`clients` (
  `id_client` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `middle_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `passport` INT NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`id_client`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bank`.`bank_accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank`.`bank_accounts` (
  `number` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `balance` INT NOT NULL,
  `client_id` INT NOT NULL,
  PRIMARY KEY (`number`),
  INDEX `client_id_idx` (`client_id` ASC) VISIBLE,
  CONSTRAINT `client_id`
    FOREIGN KEY (`client_id`)
    REFERENCES `bank`.`clients` (`id_client`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bank`.`transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank`.`transactions` (
  `id_transaction` INT NOT NULL AUTO_INCREMENT,
  `amount` INT NOT NULL,
  `data` DATETIME NOT NULL,
  `debiting_account` INT NOT NULL,
  `crediting_account` INT NOT NULL,
  PRIMARY KEY (`id_transaction`),
  INDEX `debiting_account_idx` (`debiting_account` ASC) VISIBLE,
  INDEX `crediting_account_idx` (`crediting_account` ASC) VISIBLE,
  CONSTRAINT `debiting_account`
    FOREIGN KEY (`debiting_account`)
    REFERENCES `bank`.`bank_accounts` (`number`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `crediting_account`
    FOREIGN KEY (`crediting_account`)
    REFERENCES `bank`.`bank_accounts` (`number`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
